spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO}
          clone-on-start: true
          default-label: main

  security:
    user:
      name: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASSWORD}

server:
  port: ${CONFIG_SERVER_PORT:8012}

encrypt:
  key: ${ENCRYPTION_KEY}


#test
#after change
#management:
#  endpoints:
#    web:
#      exposure:
#        include: busrefresh

