kafka-user:
  hostname: zhopa_osla

spring:
  security:
    user:
      name: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASSWORD}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info

#test
#after change
#management:
#  endpoints:
#    web:
#      exposure:
#        include: busrefresh
server:
  port: 8012
