name: First Workflow
on:
  push:
    branches:
      - 'release/**'

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "Some text"


      - name: Copy Files
        run: |
          git init
          git remote add origin https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git fetch origin
          git checkout master
      - name: List files
        run: |
          ls -a
