name: First Workflow
on: push

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "Some text"

      - uses: actions/checkout@v4

      - name: List files
        run: |
          pwd
