name: First Workflow
on: push
#  push:
#    branches:
#      - 'release/**'

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Copy Files
        run: |
          git init
          git remote add origin https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git fetch origin
          git checkout master
          ls -a
      - name: Build jar
        run: |
          export GITHUB_USERNAME=$GITHUB_ACTOR
          export GITHUB_PACKAGE_KEY=${{secrets.GITHUB_TOKEN}}
        
          chmod +x gradlew
          ./gradlew bootJar
          ls -a
