name: First Workflow
on: push
#  push:
#    branches:
#      - 'release/**'

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Copy Files
        run: |
          git init
          git remote add origin https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git fetch origin
          git checkout master
          ls -a

      - name: Build jar
        run: |
          export GITHUB_USERNAME=$GITHUB_ACTOR
          export GITHUB_PACKAGE_KEY=${{secrets.GITHUB_TOKEN}}
        
          chmod +x gradlew
          ./gradlew bootJar
          ls -a

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#        with:
#          images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/my-docker-hub-namespace/my-docker-hub-repository
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true