name: First Workflow
on: push
#  push:
#    branches:
#      - 'release/**'

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Copy Files
        run: |
          git init
          git remote add origin https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git
          git fetch origin
          git checkout master
          ls -a

      - name: Build jar
        run: |
          export GITHUB_USERNAME=$GITHUB_ACTOR
          export GITHUB_PACKAGE_KEY=${{secrets.GITHUB_TOKEN}}
          
          chmod +x gradlew
          ./gradlew bootJar
          ls -a

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mrshoffen/task-tracker-config-server:latest
